### ISSUE TITLE
Не отображает medical_doc

### ISSUE THREAD

**Issue by gordienko** [Elsant/omniauth-esia#4]
При запросе следующего scope: 'fullname snils medical_doc inn', возвращает все, кроме medical_doc.

**Comment by gordienko** [comment]
Возможно имеет смысл добавить нечто подобное

```ruby
def get_docs
        access_token.get("/rs/prns/#{uid}/docs?embed=(elements)").parsed['elements']
rescue => e
        {}
end
```

**Comment by Elsant** [comment]
Я сецмально не вводил  у себя доп запросы. Их всегда можно добавить локально по желанию, переоткрыв классв файле "#{Rails.root}/lib/omniauth/strategies/esia.rb
```
module OmniAuth
  module Strategies
    class Esia < OmniAuth::Strategies::OAuth2
     def get_docs
        access_token.get("/rs/prns/#{uid}/docs?embed=(elements)").parsed['elements']
     rescue => e
        {}
     end
   end
 end
end
```

**Comment by gordienko** [comment]
Понятно, спасибо за ответ
