### ISSUE TITLE
Rails 6

### ISSUE THREAD

**Issue by nikolaokonesh** [Elsant/omniauth-esia#8]
Добрый день! За ранее извиняюсь, за задаваемые вопросы, хоть и не уместно здесь.
Первое: работает ли gem в Rails 6 - Ruby 2.7 ? 
Второе: где взять private.key и certificate.crt? 
То что в мануале закачал а там сертификаты с расширением .cer

Спасибо.

**Comment by Elsant** [comment]
Rails 6 - Ruby 2.7 пока не тестировал. Но тут надо смотреть, работает ли omniauth-oauth2 , так omniauth-esia надстройка над ним и devise. Ключи дает Минсвязи и, по-моему, только госкомпаниям.  private.key и certificate.crt можно сделатьт из *.cer. Погуглите.
